### ISSUE TITLE
Failing to load evdev

### ISSUE THREAD

**Issue by petjb** [christopheraue/ruby-evdev#7]
Hi,

I'm trying to load `ruby-evdev` on a Raspberry Pi box, running Ubuntu Server (32-bit).

I've installed the gem using `sudo gem install evdev`, which worked fine.

If I fire up an irb session (with or without sudo), and  try to require evdev, I get the following error:

```
irb(main):001:0> require 'evdev'
Traceback (most recent call last):
       12: from /usr/bin/irb:23:in `<main>'
       11: from /usr/bin/irb:23:in `load'
       10: from /usr/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        9: from (irb):1
        8: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:149:in `require'
        7: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:160:in `rescue in require'
        6: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:160:in `require'
        5: from /var/lib/gems/2.7.0/gems/evdev-1.0.0/lib/evdev.rb:2:in `<top (required)>'
        4: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        3: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        2: from /var/lib/gems/2.7.0/gems/libevdev-1.1.1/lib/libevdev.rb:3:in `<top (required)>'
        1: from /var/lib/gems/2.7.0/gems/libevdev-1.1.1/lib/libevdev.rb:3:in `require'
LoadError (cannot load such file -- linux_input)
```

I've tried installing the `libevdev` gem also, but that didn't seem to help.

Looking at `/var/lib/gems/2.7.0/gems/libevdev-1.1.1/lib/libevdev.rb`, it looks like the error is coming from an issue with the line:

```
require 'linux_input'
```

...but if I run `require 'linux_input'` in an IRB session, no error is thrown.

Any help would be greatly appreciated - thank you.

**Comment by petjb** [comment]
Never mind, I'm an idiot.
